getCompanies:
  path: "/{sid}/companies"
  requirements: []
  method: "GET"
  queryParameters: ["name", "page", "limit"]

getCompanyById:
  path: "/{sid}/company/{id}"
  requirements:
    id: \d+
  method: "GET"
  queryParameters: []

getCompaniesByIds:
  path: "/{sid}/companies"
  requirements: []
  method: "POST"
  queryParameters: []

getNonexistentEndpoint:
  path: "/{sid}/non-existent"
  requirements: []
  method: "POST"
  queryParameters: []

getRateCategories:
  path: "/{sid}/rate-categories"
  requirements: []
  method: "GET"
  queryParameters: ["label"]

getTaxes:
  path: "/{sid}/taxes"
  requirements: []
  method: "GET"
  queryParameters: ["rate"]

createInvoice:
  path: "/{sid}/invoice"
  requirements: []
  method: "POST"
  queryParameters: []
