getCompanies:
  path: "/companies"
  requirements: []
  method: "GET"
  queryParameters: ["name", "page", "limit"]

getCompanyById:
  path: "/company/{id}"
  requirements:
    id: \d+
  method: "GET"
  queryParameters: []

getCompaniesByIds:
  path: "/companies"
  requirements: []
  method: "POST"
  queryParameters: []

getNonexistentEndpoint:
  path: "/non-existent"
  requirements: []
  method: "POST"
  queryParameters: []

getRateCategories:
  path: "/rate-categories"
  requirements: []
  method: "GET"
  queryParameters: ["label"]

getTaxes:
  path: "/taxes"
  requirements: []
  method: "GET"
  queryParameters: ["rate"]

createInvoice:
  path: "/invoice"
  requirements: []
  method: "POST"
  queryParameters: []

getShippingCompanies:
  path: "/items"
  requirements: []
  method: "GET"
  queryParameters: []
